### ISSUE TITLE
Parse errors in scenarioOutline cause tests to pass with no tests run

### ISSUE THREAD

**Issue by limitedmage** [dotnetprofessional/LiveDoc#23]
If there is a parse error in the scenarioOutline data tables, the scenario doesn't run and tests pass, Tests should fail instead.

**Comment by dotnetprofessional** [comment]
A change in the next release 0.3.x will resolve this issue. However, the behavior will be that any conversion failures will return the original text string. In the case identified here, it means the original text will be return which should cause a test failure. This issue is also related to #26

**Comment by dotnetprofessional** [comment]
Fixed for next release v0.3.0
