### ISSUE TITLE
Code gets formatted by plugin

### ISSUE THREAD

**Issue by dotnetprofessional** [dotnetprofessional/LiveDoc#51]
When you have code that 'looks' like a table the VSPlugin will mistakenly format it as if it were a Gherkin Data table. The following demonstrates the issue:

```js
        if (typeof position !== 'number' || !isFinite(position) || Math.floor(position) !== position || position > subjectString.length) {
            position = subjectString.length;
        }
```
results in:
```js
        | if (typeof position !== 'number' |  | !isFinite(position) |  | Math.floor(position) !== position |  | position > subjectString.length) { |
            position = subjectString.length;
        }
```
Other examples:
```js
} else if (line.startsWith("|") && line.endsWith("|")) {
```
```js
| } else if (line.startsWith(" | ") && line.endsWith(" | ")) { |
```

**Comment by rdmchenry** [comment]
Have you built a fresh package from the source and tried installing and reproing with that?

It looks like you are using an old version of the plugin as I know I changed it to find tables by the first character in the line being a pipe. The behavior you are seeing looks like the original regex logic I had.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dotnetprofessional** [comment]
Oh ok. Maybe I was on the Mac. I'll test tomorrow. Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
