### ISSUE TITLE
LiveDoc compatibility with Typescript and Istanbul sourcemap for code coverage

### ISSUE THREAD

**Issue by bbohec** [dotnetprofessional/LiveDoc#87]
Hello,

Since LiveDoc is show as Typescript and as a Mocha extension, I assume that it can be run on pure Typescript projects without having to translate files to use ts-node package?
If yes, could you update the documentation with Typescript configuration template?

Another question, since it's possible to user Istanbul with Mocha/Chai in order to have code coverage, does Istanbul is able to check project code coverage while writing BDD Gherkin specifications with LiveDoc instead of using only common Mocha/Chai test ways like 'describe', 'it', 'should' and keeping TS sourcemap?
If yes, could you update the documentation with an expected required additional configuration for code coverage/sourcemap if necessary?

Thanks a lot for this LiveDoc package.

**Comment by dotnetprofessional** [comment]
I'll take a look at your issues today.

**Comment by dotnetprofessional** [comment]
Thanks for the suggestion. I've added the following page on configuring Istanbul. Please let me know if this doesn't resolve your issue.

[Code Coverage](https://github.com/dotnetprofessional/LiveDoc/blob/master/packages/livedoc-mocha/docs/code-coverage.md)
