### ISSUE TITLE
Typescript / import 'livedoc-mocha'; Cannot use import statement outside a module

### ISSUE THREAD

**Issue by bbohec** [dotnetprofessional/LiveDoc#88]
Hello,

I've installed the livedoc VSCode extension is installed.

I'm trying the tutorial file .../livedoc-mocha/_src/test/Sample/Tutorial/Tutorial.Spec.ts and I added the Typescript import 'livedoc-mocha'; at the beginning. The .ts file is put in ./backlog

There is an error message on mocha test run :
```
> mocha --ui livedoc-mocha --reporter livedoc-mocha/livedoc-spec --recursive ./backlog/*.ts

Error:
Message: Cannot use import statement outside a module
import 'livedoc-mocha';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Array.forEach (<anonymous>)
    at internal/main/run_main_module.js:17:11 
```

Tested with livedoc-mocha and livedoc-mocha@beta

You can find my package.json if it can help:

```
{
  "name": "tdd",
  "version": "0.0.1",
  "description": "",
  "main": "index.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "test": "mocha --ui livedoc-mocha --reporter livedoc-mocha/livedoc-spec --recursive ./backlog/*.ts",
    "coverage": "nyc npm test"
  },
  "nyc": {
    "extension": [
      ".ts",
      ".tsx"
    ],
    "exclude": [
      "**/*.d.ts",
      "**/coverage/"
    ],
    "reporter": [
      "text",
      "html",
      "json"
    ],
    "require": [
      "ts-node/register"
    ],
    "sourceMap": true,
    "instrument": true,
    "all": true
  },
  "author": "benjamin bohec",
  "license": "UNLICENSED",
  "private": true,
  "devDependencies": {
    "@types/chai": "^4.2.5",
    "@types/mocha": "^5.2.7",
    "chai": "^4.2.0",
    "livedoc-mocha": "^0.4.0-beta-7",
    "mocha": "^6.2.2",
    "nyc": "^14.1.1",
    "source-map-support": "^0.5.16",
    "ts-node": "^8.5.2",
    "typescript": "^3.7.2"
  }
}

```

**Comment by dotnetprofessional** [comment]
You need to compile your `ts` code to javascript. Typescript code must be transpiled before it can be used. Try executing the following command and then point the test to your output folder (ie not .ts):

```
tsc -p . 
```

If you want the code to be automatically built every time you change a file (recommended). You can use this command:

```
tsc --watch -p .
```

You can also refer to the commands used in the projects source for more details or the [typescript documentation](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html).

> You can also update to the latest stable version. Ie version `0.4.1`.

I see that you're also using `nyc`, which doesn't require you to precompile the code if configured correctly. Please refer to the docs on [Code Coverage](https://github.com/dotnetprofessional/LiveDoc/blob/master/packages/livedoc-mocha/docs/code-coverage.md) for more details. Though this must be executed via the `nyc` command and not directly as your issues indicates.
